# Generated by Django 3.0.6 on 2020-05-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='grammarParticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hiragana', models.CharField(max_length=200)),
            ],
        ),
    ]
