# Generated by Django 3.0.6 on 2020-05-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanji', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammarparticle',
            name='example_words',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='grammarparticle',
            name='story',
            field=models.CharField(default='', max_length=200),
        ),
    ]
