# Generated by Django 3.0.6 on 2020-05-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanji', '0002_auto_20200528_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammarparticle',
            name='translation',
            field=models.CharField(default='', max_length=200),
        ),
    ]
