# Generated by Django 3.0.6 on 2020-05-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanji', '0003_grammarparticle_translation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grammarparticle',
            name='story',
            field=models.CharField(default='', max_length=500),
        ),
    ]
