# Generated by Django 3.0.6 on 2020-05-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanji', '0005_grammarparticle_testing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grammarparticle',
            name='example_words',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='grammarparticle',
            name='story',
            field=models.TextField(default='', max_length=500),
        ),
    ]
