# Generated by Django 3.0.6 on 2020-05-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanji', '0007_remove_grammarparticle_testing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grammarparticle',
            name='example_words',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='grammarparticle',
            name='story',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='grammarparticle',
            name='translation',
            field=models.TextField(default=''),
        ),
    ]
