# Generated by Django 3.0.6 on 2020-05-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanji', '0009_grammarparticle_radical'),
    ]

    operations = [
        migrations.CreateModel(
            name='radicals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radical', models.CharField(default='', max_length=20)),
                ('description', models.TextField()),
            ],
        ),
    ]
